//! Prints real MLS blobs for the contract v1.7 examples (`contract/v1/examples/*`), as JSON on
//! stdout. Root pastes them into the example files; this binary never touches `contract/`.
//!
//!   cd crypto && ~/.cargo/bin/cargo run -q -p risime-mls --example gen-contract-fixtures > /tmp/fixtures.json
//!
//! The attestation key is a fixed **test** key (seed below). Its JWK is printed as
//! `attestation_keys` and is never a production key. MLS keys are fresh on every run, so
//! the blobs change each time. Every blob is checked before printing: Bob joins from the
//! Welcome, decrypts the message and processes the second commit.

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as B64;
use risime_mls::{Client, DeviceId, Incoming, TestAttestor};
use serde_json::json;

/// Same users and devices as the existing contract examples.
const ALICE: &str = "7e3f1a2b-9c8d-4e5f-a6b7-c8d9e0f1a2b3";
const ALICE_PHONE: &str = "c0a80101-0000-4000-8000-000000000001";
const ALICE_TABLET: &str = "c0a80101-0000-4000-8000-000000000003";
const BOB: &str = "0b9d7e8a-1c2f-4a3b-8d4e-5f6a7b8c9d0e";
const BOB_PHONE: &str = "c0a80101-0000-4000-8000-000000000002";
const IAT: u64 = 1_791_276_930; // 2026-10-06T08:55:30Z

fn b64(b: &[u8]) -> String {
    B64.encode(b)
}

fn device(a: &TestAttestor, user: &str, dev: &str) -> (Client, String) {
    let mut c = Client::open(
        std::sync::Arc::new(risime_mls::MemoryKvStore::new()),
        DeviceId::new(user, dev).unwrap(),
        a.anchors(),
    )
    .unwrap();
    let jws = a.attest(c.device(), &c.signature_public_key(), IAT);
    c.set_attestation(&jws).unwrap();
    (c, jws)
}

fn main() {
    let attestor = TestAttestor::from_seed(*b"risime-contract-fixtures-test-k!");
    let (alice, alice_att) = device(&attestor, ALICE, ALICE_PHONE);
    let (bob, bob_att) = device(&attestor, BOB, BOB_PHONE);
    let (tablet, tablet_att) = device(&attestor, ALICE, ALICE_TABLET);

    let conversation_id = format!("dm:{BOB}_{ALICE}");
    let generation = 1;
    let group_id = format!("{conversation_id}#{generation}");
    let g = group_id.as_bytes();

    let bob_kps = bob.generate_key_packages(2).unwrap();
    let bob_last_resort = bob.generate_last_resort_key_package().unwrap();

    // Epoch 0: Alice creates the group with Bob's phone.
    let create = alice
        .create_group(g, std::slice::from_ref(&bob_kps[0]))
        .unwrap();
    assert_eq!(alice.commit_accepted(g).unwrap(), 1);
    let welcome = create.welcome.clone().unwrap();
    let joined = bob.join_from_welcome(&welcome).unwrap();
    assert_eq!(joined.epoch, 1);

    // Epoch 1: an application message from Alice.
    let plaintext = "Hello Bob — this is end-to-end encrypted.";
    let ciphertext = alice.encrypt(g, plaintext.as_bytes()).unwrap();
    assert_eq!(bob.decrypt(g, &ciphertext).unwrap(), plaintext.as_bytes());

    // Epoch 1 -> 2: Alice's phone adds her tablet (mls_membership "added").
    let tablet_kp = tablet.generate_key_packages(1).unwrap().remove(0);
    let add_tablet = alice
        .add_members(g, std::slice::from_ref(&tablet_kp))
        .unwrap();
    assert_eq!(alice.commit_accepted(g).unwrap(), 2);
    assert!(matches!(
        bob.process(g, &add_tablet.commit).unwrap(),
        Incoming::Commit { epoch: 2, .. }
    ));
    let tablet_welcome = add_tablet.welcome.clone().unwrap();
    tablet.join_from_welcome(&tablet_welcome).unwrap();

    let ids = |v: &[DeviceId]| -> Vec<serde_json::Value> {
        v.iter()
            .map(|d| json!({"user_id": d.user_id, "device_id": d.device_id}))
            .collect()
    };
    let out = json!({
        "_note": "Generated by crypto/risime-mls/examples/gen-contract-fixtures.rs. TEST attestation key only. MLS blobs are fresh per run.",
        "attestation_keys": {"keys": [serde_json::from_str::<serde_json::Value>(&attestor.public_jwk()).unwrap()]},
        "conversation_id": conversation_id,
        "generation": generation,
        "group_id": group_id,
        "devices": {
            "alice_phone": {"user_id": ALICE, "device_id": ALICE_PHONE, "signature_key": b64(&alice.signature_public_key()), "attestation": alice_att},
            "alice_tablet": {"user_id": ALICE, "device_id": ALICE_TABLET, "signature_key": b64(&tablet.signature_public_key()), "attestation": tablet_att},
            "bob_phone": {"user_id": BOB, "device_id": BOB_PHONE, "signature_key": b64(&bob.signature_public_key()), "attestation": bob_att},
        },
        "device_put_mls": {"mls": {"signature_key": b64(&bob.signature_public_key())}},
        "device_put_mls_reply": {"attestation": bob_att},
        "key_packages_upload": {
            "key_packages": bob_kps.iter().map(|k| b64(k)).collect::<Vec<_>>(),
            "last_resort": b64(&bob_last_resort),
        },
        "key_package": b64(&bob_kps[1]),
        "last_resort": b64(&bob_last_resort),
        "mls_commit_request_create": {
            "generation": generation,
            "epoch": create.epoch,
            "commit": b64(&create.commit),
            "welcome": b64(&welcome),
            "added": ids(&create.added),
            "removed": [],
        },
        "mls_commit_request_add_device": {
            "generation": generation,
            "epoch": add_tablet.epoch,
            "commit": b64(&add_tablet.commit),
            "welcome": b64(&tablet_welcome),
            "added": ids(&add_tablet.added),
            "removed": [],
        },
        "event_mls_commit": {
            "conversation_id": format!("dm:{BOB}_{ALICE}"),
            "generation": generation,
            "epoch": add_tablet.epoch,
            "commit": b64(&add_tablet.commit),
            "from_device": ALICE_PHONE,
        },
        "event_mls_welcome": {
            "conversation_id": format!("dm:{BOB}_{ALICE}"),
            "generation": generation,
            "epoch": 1,
            "welcome": b64(&welcome),
            "to_devices": [BOB_PHONE],
        },
        "msg_send_e2ee": {
            "to": BOB,
            "ciphertext": b64(&ciphertext),
            "generation": generation,
            "epoch": 1,
        },
        "plaintext_of_ciphertext": plaintext,
    });
    println!("{}", serde_json::to_string_pretty(&out).unwrap());
}
