import Config

# Configure your database
# The password comes from the repo `.env` (see config/runtime.exs).
config :risime, RisiMe.Repo,
  username: "risime",
  hostname: "127.0.0.1",
  # RISIME_DEV_DB / RISIME_DEV_KEYSPACE let scripts/interop use its own store (risime_interop),
  # never the pilot's risime_dev.
  database: System.get_env("RISIME_DEV_DB", "risime_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :risime, RisiMeWeb.Endpoint,
  # spark2 has a public IP: always bind to loopback. secret_key_base comes from `.env`.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  # scripts/interop and scripts/upgrade-test run temp servers with RISIME_CODE_RELOADER=false and
  # their own MIX_BUILD_PATH, so other sessions' compiles in this checkout can't stall them.
  code_reloader: System.get_env("RISIME_CODE_RELOADER", "true") == "true",
  debug_errors: true,
  watchers: []

config :risime, :cassandra,
  nodes: ["127.0.0.1:9042"],
  keyspace: System.get_env("RISIME_DEV_KEYSPACE", "risime_dev"),
  # Connections to the node; each carries up to 100 concurrent requests (docs/status/loadtest.md).
  pool_size: 16

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :risime, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Dev login (/auth/request + /auth/verify, opaque tokens) for the local/test server.
config :risime, :dev_local_auth, true
