defmodule RisiMeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :risime

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_risime_key",
    signing_salt: "LRwbQIMm",
    same_site: "Lax"
  ]

  socket "/socket", RisiMeWeb.UserSocket,
    websocket: [connect_info: [:peer_data, :x_headers]],
    longpoll: false,
    auth_token: true

  # Contract v1.3 §6.2: the socket upgrade takes `Authorization: Bearer <token>`. Phoenix only
  # exposes the channels client's subprotocol token as `connect_info[:auth_token]`, so the
  # header is copied there before socket dispatch (a subprotocol token, if sent, wins).
  def call(%Plug.Conn{path_info: ["socket", "websocket"]} = conn, opts) do
    conn =
      case Plug.Conn.get_req_header(conn, "authorization") do
        ["Bearer " <> token] ->
          Plug.Conn.put_private(conn, :phoenix_transport_auth_token, String.trim(token))

        _ ->
          conn
      end

    super(conn, opts)
  end

  def call(conn, opts), do: super(conn, opts)

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :risime,
    gzip: not code_reloading?,
    only: RisiMeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :risime
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug RisiMeWeb.Router
end
